import{createHash,createHmac,randomUUID}from'node:crypto';
import type{APIContext}from'./handlers.js';
import type{CGRequest,CGResponse}from'./middleware.js';
import{jsonResponse,errorResponse}from'./middleware.js';
export type WebhookEvent='timepoint.created'|'domain.registered'|'domain.published'|'segment.allocated'|'file.created'|'file.tombstoned';
export interface WebhookSubscription{id:string;url:string;events:WebhookEvent[];secret:string;active:boolean;created_at:bigint;}
const _subs=new Map<string,WebhookSubscription>();
const _dels:Array<{id:string;sub_id:string;event:WebhookEvent;status:string;attempts:number;created_at:bigint}>=[];
export function signPayload(secret:string,body:string):string{return'sha256='+createHmac('sha256',secret).update(body).digest('hex');}
export function verifySignature(secret:string,body:string,sig:string):boolean{const exp=signPayload(secret,body);try{const a=Buffer.from(exp,'utf8'),b=Buffer.from(sig,'utf8');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=(a[i]!^b[i]!);return d===0;}catch{return false;}}
export async function dispatchEvent(event:WebhookEvent,data:unknown):Promise<void>{const body=JSON.stringify({id:randomUUID(),event,created_at:new Date().toISOString(),data});for(const sub of _subs.values()){if(!sub.active||!sub.events.includes(event))continue;const d={id:randomUUID(),sub_id:sub.id,event,status:'pending',attempts:0,created_at:BigInt(Date.now())*1_000_000n};_dels.push(d);void fetch(sub.url,{method:'POST',headers:{'Content-Type':'application/json','X-ChronoGrid-Signature':signPayload(sub.secret,body)},body,signal:AbortSignal.timeout(10000)}).then(r=>{d.status=r.ok?'delivered':'failed';d.attempts=1;}).catch(()=>{d.status='failed';d.attempts=1;});}}
export async function postWebhook(req:CGRequest,_c:APIContext):Promise<CGResponse>{try{const b=req.body as Record<string,unknown>;if(!b['url']||!b['events'])return jsonResponse(422,{message:'url+events'});const sub:WebhookSubscription={id:randomUUID(),url:b['url'] as string,events:b['events'] as WebhookEvent[],secret:(b['secret'] as string)||createHash('sha256').update(randomUUID()).digest('hex').slice(0,32),active:true,created_at:BigInt(Date.now())*1_000_000n};_subs.set(sub.id,sub);return jsonResponse(201,{id:sub.id,url:sub.url,events:sub.events,active:sub.active,secret:sub.secret,created_at:sub.created_at.toString()});}catch(e){return errorResponse(e);}}
export async function listWebhooks(_r:CGRequest,_c:APIContext):Promise<CGResponse>{return jsonResponse(200,{items:[..._subs.values()].map(s=>({id:s.id,url:s.url,events:s.events,active:s.active,created_at:s.created_at.toString()}))});}
export async function getWebhookDeliveries(_r:CGRequest,_c:APIContext):Promise<CGResponse>{return jsonResponse(200,{items:_dels.map(d=>({...d,created_at:d.created_at.toString()}))});}
export async function deleteWebhook(req:CGRequest,_c:APIContext):Promise<CGResponse>{const s=_subs.get(req.params['id']!);if(!s)return jsonResponse(404,{message:'Nicht gefunden'});_subs.set(s.id,{...s,active:false});return jsonResponse(200,{message:'Deaktiviert'});}
