// suite/skip/skipReason werden von den Suiten seit jeher gesetzt (Gruppenname,
// pending-Stubs in t-l3-pending.ts), standen aber nie im Interface — jedes
// betroffene Objektliteral erzeugte einen TS2353. Nur die Deklaration wird
// nachgezogen; runTests ignoriert die Felder weiterhin, die skip-Auswertung
// liegt in cli.ts.
export interface TestCase{id:string;description:string;level:1|2|3;tags?:string[];suite?:string;skip?:boolean;skipReason?:string;run:()=>unknown|Promise<unknown>;expected:unknown;}
export interface TestResult{id:string;description:string;level:1|2|3;passed:boolean;error?:string;durationMs:number;}
export async function runTests(tests:TestCase[],maxLevel=3):Promise<TestResult[]>{const results:TestResult[]=[];for(const t of tests.filter(t=>t.level<=maxLevel)){const start=Date.now();try{const actual=await t.run();const passed=deepEqual(actual,t.expected);results.push({id:t.id,description:t.description,level:t.level,passed,durationMs:Date.now()-start,error:passed?undefined:`Erwartet: ${JSON.stringify(t.expected)}, Erhalten: ${JSON.stringify(actual)}`});}catch(err){results.push({id:t.id,description:t.description,level:t.level,passed:false,durationMs:Date.now()-start,error:err instanceof Error?err.message:String(err)});}}return results;}
function deepEqual(a:unknown,b:unknown):boolean{if(a===b)return true;if(typeof a!==typeof b)return false;if(typeof a==='bigint'&&typeof b==='bigint')return a===b;if(Array.isArray(a)&&Array.isArray(b)){if(a.length!==b.length)return false;return a.every((v,i)=>deepEqual(v,b[i]));}if(typeof a==='object'&&a!==null&&typeof b==='object'&&b!==null){const ka=Object.keys(a as object).sort(),kb=Object.keys(b as object).sort();if(!deepEqual(ka,kb))return false;return ka.every(k=>deepEqual((a as Record<string,unknown>)[k],(b as Record<string,unknown>)[k]));}return false;}
