import type{CGTimepoint,CGDomain,CGManifest,CGRelation,CGUASegment}from'cg-types/domain.js';
import{Errors}from'cg-types/errors.js';import{SegmentRegistry}from'cg-cguas/cguas.js';
export interface ITimepointRepository{insert(tp:CGTimepoint):Promise<void>;findById(id:string):Promise<CGTimepoint|null>;list(limit?:number,offset?:number):Promise<CGTimepoint[]>;}
export interface IDomainRepository{insert(d:CGDomain):Promise<void>;findByNameVersion(n:string,v:string):Promise<CGDomain|null>;list():Promise<CGDomain[]>;publish(n:string,v:string):Promise<void>;}
export interface IManifestRepository{insert(m:CGManifest):Promise<void>;findByCGFI(cgfi:string):Promise<CGManifest|null>;tombstone(cgfi:string):Promise<void>;}
export interface IRelationRepository{insert(r:CGRelation):Promise<void>;list():Promise<CGRelation[]>;}
export interface ISegmentRepository{allocate(g:string,s:bigint,p?:string):Promise<CGUASegment>;resolve(id:string):Promise<CGUASegment>;revoke(id:string):Promise<void>;list():Promise<CGUASegment[]>;}
export class InMemoryTimepointRepository implements ITimepointRepository{private readonly s=new Map<string,CGTimepoint>();async insert(tp:CGTimepoint):Promise<void>{this.s.set(tp.machine_id,tp);}async findById(id:string):Promise<CGTimepoint|null>{return this.s.get(id)??null;}async list(l=100,o=0):Promise<CGTimepoint[]>{return[...this.s.values()].slice(o,o+l);}}
export class InMemoryDomainRepository implements IDomainRepository{private readonly s=new Map<string,CGDomain>();async insert(d:CGDomain):Promise<void>{const k=`${d.name}@${d.version}`;if(this.s.has(k))throw Errors.SemanticError.duplicateName(k);this.s.set(k,d);}async findByNameVersion(n:string,v:string):Promise<CGDomain|null>{return this.s.get(`${n}@${v}`)??null;}async list():Promise<CGDomain[]>{return[...this.s.values()];}async publish(n:string,v:string):Promise<void>{const d=this.s.get(`${n}@${v}`);if(!d)throw Errors.VersionError.notFound(`${n}@${v}`);if(d.published)throw Errors.CGFSError.wormViolation('Bereits publiziert');this.s.set(`${n}@${v}`,{...d,published:true,published_at:BigInt(Date.now())*1_000_000n});}}
export class InMemoryManifestRepository implements IManifestRepository{private readonly s=new Map<string,CGManifest>();async insert(m:CGManifest):Promise<void>{this.s.set(m.cgfi,m);}async findByCGFI(cgfi:string):Promise<CGManifest|null>{return this.s.get(cgfi)??null;}async tombstone(cgfi:string):Promise<void>{const m=this.s.get(cgfi);if(!m)throw Errors.CGFSError.fileNotFound(cgfi);this.s.set(cgfi,{...m,tombstone:true});}}
export class InMemoryRelationRepository implements IRelationRepository{private readonly s:CGRelation[]=[];async insert(r:CGRelation):Promise<void>{this.s.push(r);}async list():Promise<CGRelation[]>{return[...this.s];}}
export class InMemorySegmentRepository implements ISegmentRepository{private readonly r=new SegmentRegistry();async allocate(g:string,s:bigint,p?:string):Promise<CGUASegment>{return this.r.allocate(g,s,p);}async resolve(id:string):Promise<CGUASegment>{return this.r.resolve(id);}async revoke(id:string):Promise<void>{this.r.revoke(id);}async list():Promise<CGUASegment[]>{return this.r.list();}}
