import type{TestCase}from'../runner.js';
import{issueJWT,verifyJWT,hasRole,getRequiredRole,checkAuth,extractBearer,TEST_TOKENS}from'cg-api/auth.js';
import{Errors}from'cg-types/errors.js';
export const authTests:TestCase[]=[
  {id:'T-AUTH-001',level:1,description:'issueJWT 3-teilig',run:()=>issueJWT('u','reader').split('.').length,expected:3},
  {id:'T-AUTH-002',level:1,description:'admin-Token verifizierbar',run:()=>verifyJWT(issueJWT('a','admin')).role,expected:'admin'},
  {id:'T-AUTH-003',level:1,description:'writer-Token',run:()=>verifyJWT(issueJWT('w','writer')).role,expected:'writer'},
  {id:'T-AUTH-004',level:1,description:'reader-Token',run:()=>verifyJWT(issueJWT('r','reader')).role,expected:'reader'},
  {id:'T-AUTH-005',level:1,description:'sub korrekt',run:()=>verifyJWT(issueJWT('kurt','admin')).sub,expected:'kurt'},
  {id:'T-AUTH-006',level:1,description:'ungültiges Token',run:()=>{try{verifyJWT('x.y.z');return'ok';}catch(e){return(e as{code:string}).code;}},expected:'CG-E-012.003'},
  {id:'T-AUTH-007',level:1,description:'manipuliertes Token',run:()=>{const t=issueJWT('u','reader');const[h,p,s]=t.split('.');const pl=JSON.parse(Buffer.from(p!,'base64url').toString());pl.role='admin';const fake=`${h}.${Buffer.from(JSON.stringify(pl)).toString('base64url')}.${s}`;try{verifyJWT(fake);return'ok';}catch(e){return(e as{code:string}).code;}},expected:'CG-E-012.003'},
  {id:'T-AUTH-008',level:1,description:'abgelaufenes Token',run:()=>{const t=issueJWT('u','reader',-1);try{verifyJWT(t);return'ok';}catch(e){return(e as{code:string}).code;}},expected:'CG-E-012.004'},
  {id:'T-AUTH-009',level:2,description:'leeres Token',run:()=>{try{verifyJWT('');return'ok';}catch(e){return(e as{code:string}).code;}},expected:'CG-E-012.003'},
  {id:'T-AUTH-010',level:1,description:'hasRole admin>=admin',run:()=>hasRole('admin','admin'),expected:true},
  {id:'T-AUTH-011',level:1,description:'hasRole admin>=writer',run:()=>hasRole('admin','writer'),expected:true},
  {id:'T-AUTH-012',level:1,description:'hasRole admin>=reader',run:()=>hasRole('admin','reader'),expected:true},
  {id:'T-AUTH-013',level:1,description:'hasRole writer>=reader',run:()=>hasRole('writer','reader'),expected:true},
  {id:'T-AUTH-014',level:1,description:'hasRole reader!>=writer',run:()=>hasRole('reader','writer'),expected:false},
  {id:'T-AUTH-015',level:1,description:'hasRole writer!>=admin',run:()=>hasRole('writer','admin'),expected:false},
  {id:'T-AUTH-016',level:1,description:'health ist public',run:()=>getRequiredRole('GET','/v1/health'),expected:'public'},
  {id:'T-AUTH-017',level:1,description:'openapi ist public',run:()=>getRequiredRole('GET','/v1/openapi.json'),expected:'public'},
  {id:'T-AUTH-018',level:1,description:'GET timepoints=reader',run:()=>getRequiredRole('GET','/v1/timepoints'),expected:'reader'},
  {id:'T-AUTH-019',level:1,description:'POST timepoints=writer',run:()=>getRequiredRole('POST','/v1/timepoints'),expected:'writer'},
  {id:'T-AUTH-020',level:1,description:'DELETE files=writer',run:()=>getRequiredRole('DELETE','/v1/files/abc'),expected:'writer'},
  {id:'T-AUTH-021',level:2,description:'checkAuth public kein Token',run:()=>checkAuth(undefined,'public').authenticated,expected:true},
  {id:'T-AUTH-022',level:2,description:'checkAuth reader kein Token',run:()=>checkAuth(undefined,'reader').authenticated,expected:false},
  {id:'T-AUTH-023',level:2,description:'checkAuth reader+Token',run:()=>checkAuth(`Bearer ${issueJWT('u','reader')}`,'reader').authenticated,expected:true},
  {id:'T-AUTH-024',level:2,description:'checkAuth writer+reader-Token=403',run:()=>checkAuth(`Bearer ${issueJWT('u','reader')}`,'writer').authenticated,expected:false},
  {id:'T-AUTH-025',level:2,description:'checkAuth admin+admin-Token',run:()=>checkAuth(`Bearer ${issueJWT('u','admin')}`,'admin').authenticated,expected:true},
  {id:'T-AUTH-026',level:2,description:'extractBearer korrekt',run:()=>extractBearer('Bearer abc123'),expected:'abc123'},
  {id:'T-AUTH-027',level:2,description:'extractBearer null',run:()=>extractBearer(undefined),expected:null},
  {id:'T-AUTH-028',level:2,description:'extractBearer Basic=null',run:()=>extractBearer('Basic abc'),expected:null},
  {id:'T-AUTH-029',level:2,description:'TEST_TOKENS.admin',run:()=>verifyJWT(TEST_TOKENS.admin()).role,expected:'admin'},
  {id:'T-AUTH-030',level:2,description:'TEST_TOKENS.reader',run:()=>verifyJWT(TEST_TOKENS.reader()).role,expected:'reader'},
  {id:'T-AUTH-031',level:2,description:'CG-E-012.001 HTTP 401',run:()=>Errors.AuthError.unauthorized('t').httpStatus,expected:401},
  {id:'T-AUTH-032',level:2,description:'CG-E-012.002 HTTP 403',run:()=>Errors.AuthError.forbidden('t').httpStatus,expected:403},
  {id:'T-AUTH-033',level:3,description:'iss=chronogrid',run:()=>verifyJWT(issueJWT('u','reader')).iss,expected:'chronogrid'},
  {id:'T-AUTH-034',level:3,description:'exp>iat',run:()=>{const p=verifyJWT(issueJWT('u','reader'));return(p.exp??0)>(p.iat??0);},expected:true},
  {id:'T-AUTH-035',level:3,description:'verschiedene subs→Token',run:()=>issueJWT('alice','reader')!==issueJWT('bob','reader'),expected:true},
];
