import type { TestCase } from '../runner.js';
import { InMemoryTimepointRepository,InMemoryDomainRepository,InMemoryManifestRepository,InMemoryRelationRepository,InMemorySegmentRepository } from 'cg-storage/repository.js';
import { createRepositories } from 'cg-storage/repository-factory.js';
import { createTimepoint,computeCGFI } from 'cg-engine/engine.js';
import type { CGDomain,CGManifest,CGRelation } from 'cg-types/domain.js';
export const storageTests:TestCase[]=[
  {id:'T-STORAGE-001',level:1,description:'backend=memory',run:()=>createRepositories(undefined,'memory').backend,expected:'memory'},
  {id:'T-STORAGE-002',level:1,description:'Timepoint insert+findById',run:async()=>{const r=new InMemoryTimepointRepository();const tp=createTimepoint('TAI','1.0',1742041937n);await r.insert(tp);return(await r.findById(tp.machine_id))?.machine_id===tp.machine_id;},expected:true},
  {id:'T-STORAGE-003',level:1,description:'findById → null wenn nicht gefunden',run:async()=>new InMemoryTimepointRepository().findById('x'),expected:null},
  {id:'T-STORAGE-004',level:1,description:'list gibt 2 zurück',run:async()=>{const r=new InMemoryTimepointRepository();await r.insert(createTimepoint('TAI','1.0',1n));await r.insert(createTimepoint('TAI','1.0',2n));return(await r.list()).length;},expected:2},
  {id:'T-STORAGE-005',level:1,description:'Domain insert+find',run:async()=>{const r=new InMemoryDomainRepository();const d:CGDomain={name:'D1',version:'1.0',definition:{} as never,published:false,created_at:1n};await r.insert(d);return(await r.findByNameVersion('D1','1.0'))?.name;},expected:'D1'},
  {id:'T-STORAGE-006',level:1,description:'Domain Duplikat → CG-E-002.001',run:async()=>{const r=new InMemoryDomainRepository();const d:CGDomain={name:'DD',version:'1.0',definition:{} as never,published:false,created_at:1n};await r.insert(d);try{await r.insert(d);return false;}catch(e){return(e as{code:string}).code==='CG-E-002.001';}},expected:true},
  {id:'T-STORAGE-007',level:1,description:'Domain publish',run:async()=>{const r=new InMemoryDomainRepository();await r.insert({name:'P',version:'1.0',definition:{} as never,published:false,created_at:1n});await r.publish('P','1.0');return(await r.findByNameVersion('P','1.0'))?.published;},expected:true},
  {id:'T-STORAGE-008',level:1,description:'Manifest insert+find',run:async()=>{const r=new InMemoryManifestRepository();const cgfi=computeCGFI('t','h','pdf');await r.insert({cgfi,tai_timepoint:'t',content_hash:'h',type_id:'pdf',size_bytes:1024n,metadata:{},tombstone:false,created_at:1n});return(await r.findByCGFI(cgfi))?.cgfi===cgfi;},expected:true},
  {id:'T-STORAGE-009',level:1,description:'Manifest tombstone',run:async()=>{const r=new InMemoryManifestRepository();const cgfi=computeCGFI('t','h','pdf');await r.insert({cgfi,tai_timepoint:'t',content_hash:'h',type_id:'pdf',size_bytes:0n,metadata:{},tombstone:false,created_at:1n});await r.tombstone(cgfi);return(await r.findByCGFI(cgfi))?.tombstone;},expected:true},
  {id:'T-STORAGE-010',level:1,description:'absolute_value ist BigInt',run:async()=>{const r=new InMemoryTimepointRepository();const tp=createTimepoint('TAI','1.0',9999999999n);await r.insert(tp);return typeof(await r.findById(tp.machine_id))?.absolute_value;},expected:'bigint'},
  {id:'T-STORAGE-011',level:1,description:'Relation insert+list',run:async()=>{const r=new InMemoryRelationRepository();await r.insert({id:'r1',timepoint_a:'a',timepoint_b:'b',relation:'BEFORE',computed_at:1n});return(await r.list()).length;},expected:1},
  {id:'T-STORAGE-012',level:1,description:'Segment allocate+resolve',run:async()=>{const r=new InMemorySegmentRepository();const s=await r.allocate('t',1000n);return(await r.resolve(s.id)).status;},expected:'active'},
  {id:'T-STORAGE-013',level:2,description:'Segment revoke → CG-E-010.004',run:async()=>{const r=new InMemorySegmentRepository();const s=await r.allocate('t',1000n);await r.revoke(s.id);try{await r.resolve(s.id);return false;}catch(e){return(e as{code:string}).code==='CG-E-010.004';}},expected:true},
  {id:'T-STORAGE-014',level:2,description:'Segment list',run:async()=>{const r=new InMemorySegmentRepository();await r.allocate('a',1000n);await r.allocate('b',2000n);return(await r.list()).length;},expected:2},
  {id:'T-STORAGE-015',level:2,description:'Domain list',run:async()=>{const r=new InMemoryDomainRepository();await r.insert({name:'A',version:'1.0',definition:{} as never,published:false,created_at:1n});await r.insert({name:'B',version:'1.0',definition:{} as never,published:false,created_at:2n});return(await r.list()).length;},expected:2},
  {id:'T-STORAGE-016',level:3,description:'I-S1: Tombstone irreversibel',run:async()=>{const r=new InMemoryManifestRepository();const cgfi=computeCGFI('x','y','z');await r.insert({cgfi,tai_timepoint:'x',content_hash:'y',type_id:'z',size_bytes:0n,metadata:{},tombstone:false,created_at:1n});await r.tombstone(cgfi);return(await r.findByCGFI(cgfi))?.tombstone===true;},expected:true},
];
